import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Legacy colors (kept for any remaining references)
        'bg-base':        '#0D1117',
        'bg-surface':     '#161B22',
        'bg-elevated':    '#1C2128',
        'border-default': '#30363D',
        'border-subtle':  '#21262D',
        'text-primary':   '#E6EDF3',
        'text-muted':     '#8B949E',
        'text-faint':     '#484F58',
        'amber':          '#FFB300',
        'amber-dim':      '#2D1F00',
        'teal':           '#14B8A6',
        'teal-dim':       '#001F1E',
        'red':            '#F85149',
        'red-dim':        '#2D0F0E',
        'green':          '#3FB950',
        'green-dim':      '#0D1F0F',
        'blue':           '#388BFD',
        // Liquid Glass color system
        'outline':                  '#859398',
        'on-secondary':             '#002584',
        'secondary-fixed-dim':      '#b8c4ff',
        'on-primary-container':     '#00586b',
        'primary-fixed-dim':        '#3cd7ff',
        'surface':                  '#0d1323',
        'on-primary':               '#003642',
        'on-background':            '#dde2f9',
        'surface-container-lowest': '#080e1d',
        'surface-container':        '#191f30',
        'surface-container-low':    '#151b2c',
        'background':               '#0d1323',
        'primary-fixed':            '#b4ebff',
        'inverse-on-surface':       '#2a3041',
        'tertiary-container':       '#36d9c4',
        'on-secondary-container':   '#a0b1ff',
        'error':                    '#ffb4ab',
        'primary-container':        '#00d4ff',
        'primary':                  '#a8e8ff',
        'surface-bright':           '#33394a',
        'on-surface-variant':       '#bbc9cf',
        'secondary-fixed':          '#dde1ff',
        'tertiary':                 '#5df6e0',
        'error-container':          '#93000a',
        'secondary-container':      '#173bab',
        'surface-container-high':   '#24293b',
        'tertiary-fixed-dim':       '#3cddc7',
        'surface-container-highest':'#2f3446',
        'inverse-surface':          '#dde2f9',
        'secondary':                '#b8c4ff',
        'on-surface':               '#dde2f9',
        'outline-variant':          '#3c494e',
        'tertiary-fixed':           '#62fae3',
        'surface-tint':             '#3cd7ff',
        'on-error-container':       '#ffdad6',
        'surface-variant':          '#2f3446',
      },
      fontFamily: {
        headline: ['var(--font-space-grotesk)', 'sans-serif'],
        body: ['var(--font-inter)', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'monospace'],
        label: ['var(--font-space-grotesk)', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '8px',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      keyframes: {
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseGlow: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.4' },
        },
        livePulse: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(93, 246, 224, 0.4)' },
          '50%': { boxShadow: '0 0 0 4px rgba(93, 246, 224, 0)' },
        },
        terminalLine: {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        slideInLeft: 'slideInLeft 0.3s ease forwards',
        fadeInUp: 'fadeInUp 0.3s ease forwards',
        pulseGlow: 'pulseGlow 2s ease-in-out infinite',
        livePulse: 'livePulse 2s ease-in-out infinite',
        terminalLine: 'terminalLine 0.2s ease forwards',
      },
    },
  },
  plugins: [],
}
export default config
