import type { Memory } from '@/types/memory'
import type { CalendarEvent } from '@/types/calendar'

export const MOCK_MEMORIES: Memory[] = [
  {
    memoryId: 'MEM-001',
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    title: 'AWS ECS Deployment Pattern',
    content: `# AWS ECS Deployment Pattern\n\n## Overview\nThis memory captures the preferred deployment strategy for Hermes agent services on AWS ECS.\n\n## Key Steps\n1. Build Docker image with \`node:20-alpine\` base\n2. Push to ECR with semantic versioning tag\n3. Update task definition with new image URI\n4. ECS rolling deployment with min 50% healthy\n\n## Configuration\n\`\`\`json\n{\n  "cpu": "512",\n  "memory": "1024",\n  "networkMode": "awsvpc"\n}\n\`\`\`\n\n## Rollback Procedure\nUse \`aws ecs update-service --force-new-deployment\` if issues arise.`,
    type: 'skill',
    tags: ['aws', 'ecs', 'deployment', 'docker'],
    source: 'hermes',
    relevanceScore: 0.95,
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    version: 3,
  },
  {
    memoryId: 'MEM-002',
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    title: 'User Preference: Concise Responses',
    content: `# User Communication Preferences\n\n## Style\n- Keep responses concise and action-oriented\n- Use bullet points for multi-step processes\n- Lead with the answer, follow with context\n- Prefer code blocks over prose for technical content\n\n## Tone\n- Professional but not stiff\n- Direct, not verbose\n- Use active voice\n\n## Format\nWhen presenting options, use numbered lists. When confirming actions, use checkmarks.`,
    type: 'context',
    tags: ['preferences', 'communication', 'user'],
    source: 'hermes',
    relevanceScore: 0.88,
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    version: 2,
  },
  {
    memoryId: 'MEM-003',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    title: 'DynamoDB Table Schema — hermes-tasks',
    content: `# DynamoDB Table: hermes-tasks\n\n## Primary Key\n- Partition Key: \`taskId\` (String)\n- No sort key\n\n## Attributes\n| Field | Type | Description |\n|-------|------|-------------|\n| taskId | S | UUID v4 |\n| status | S | Task lifecycle state |\n| assignee | S | hermes \| human \| both |\n| priority | S | low \| medium \| high \| critical |\n| createdAt | S | ISO 8601 timestamp |\n\n## GSI Indexes\n- \`status-index\`: GSI on \`status\` field for filtering by column\n- \`assignee-index\`: GSI on \`assignee\` for agent task queries`,
    type: 'context',
    tags: ['dynamodb', 'schema', 'database'],
    source: 'user',
    relevanceScore: 0.92,
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    version: 1,
  },
  {
    memoryId: 'MEM-004',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    title: 'Node.js 20 Alpine Performance Improvement',
    content: `# Node 20 Alpine Upgrade Finding\n\n## Discovery\nDuring routine performance analysis, identified that upgrading from node:18-alpine to node:20-alpine reduces cold start time by ~23%.\n\n## Benchmark Results\n- node:18-alpine cold start: ~4.2s\n- node:20-alpine cold start: ~3.2s\n- Memory usage: -18% reduction\n\n## Recommendation\nUpdate all ECS task definitions to use node:20-alpine. Schedule during next maintenance window.\n\n## Risk\nLow — only affects build base image, no API changes.`,
    type: 'improvement',
    tags: ['nodejs', 'performance', 'docker', 'improvement'],
    source: 'hermes',
    relevanceScore: 0.79,
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    relatedTaskIds: ['TX-0003'],
    version: 1,
  },
  {
    memoryId: 'MEM-005',
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    title: 'CloudWatch Alerting Thresholds',
    content: `# CloudWatch Alert Configuration\n\n## Current Thresholds\n- CPU Utilization > 80% → High alarm\n- Memory Utilization > 85% → High alarm\n- Error rate > 5% in 5min → Critical alarm\n\n## Notification\nAll alarms route to SNS topic \`hermes-alerts\` → Slack webhook.\n\n## Suppression\nAlarms suppressed during scheduled maintenance windows (Sundays 02:00-04:00 UTC).`,
    type: 'context',
    tags: ['cloudwatch', 'monitoring', 'alerts'],
    source: 'hermes',
    relevanceScore: 0.84,
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    version: 1,
  },
  {
    memoryId: 'MEM-006',
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    title: 'Semantic Memory Search Strategy',
    content: `# Memory Search Optimization\n\n## Current Approach\nText-based search using DynamoDB scan with FilterExpression on title and content.\n\n## Identified Limitation\nFull-text scan is slow (O(n)) and doesn't capture semantic similarity.\n\n## Proposed Improvement\nIntegrate OpenSearch Serverless with vector embeddings:\n1. Generate embeddings on memory create/update\n2. Store in OpenSearch vector index\n3. Use kNN query for semantic search\n\n## Estimated Impact\n- Search latency: from ~800ms to ~120ms\n- Relevance quality: significant improvement`,
    type: 'improvement',
    tags: ['search', 'memory', 'optimization', 'ml'],
    source: 'hermes',
    relevanceScore: 0.71,
    updatedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    relatedTaskIds: ['TX-0006'],
    version: 1,
  },
]

export const MOCK_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    eventId: 'mock-mem-001',
    hermesJobId: 'mock-mem-001',
    scheduledAt: new Date().toISOString(),
    title: 'Memory Consolidation Run',
    type: 'cron',
    schedule: '0 2 * * *',
    scheduleDisplay: '0 2 * * *',
    prompt: 'Consolidate recent session memory into long-term storage. Summarize the day, archive completed threads, and surface anything that needs follow-up.',
    skills: ['memory'],
    state: 'scheduled',
    nextRun: new Date(new Date().setHours(26, 0, 0, 0)).toISOString(),
    lastRun: new Date(Date.now() - 86400000).toISOString(),
    lastRunStatus: 'success',
    description: 'Consolidates recent context into long-term memory storage.',
    createdBy: 'hermes',
  },
  {
    eventId: 'mock-metrics-002',
    hermesJobId: 'mock-metrics-002',
    scheduledAt: new Date().toISOString(),
    title: 'Performance Metrics Collection',
    type: 'cron',
    schedule: 'every 15m',
    scheduleDisplay: 'every 15m',
    prompt: 'Pull ECS CPU/memory metrics and post a brief health summary to #ops if anything is above 75%.',
    state: 'scheduled',
    nextRun: new Date(Date.now() + 900000).toISOString(),
    lastRun: new Date(Date.now() - 900000).toISOString(),
    lastRunStatus: 'success',
    description: 'Collects ECS CPU/memory metrics every 15 minutes.',
    createdBy: 'hermes',
  },
  {
    eventId: 'mock-review-003',
    hermesJobId: 'mock-review-003',
    scheduledAt: new Date().toISOString(),
    title: 'Weekly Task Review',
    type: 'cron',
    schedule: '0 9 * * MON',
    scheduleDisplay: '0 9 * * MON',
    prompt: 'Analyze last week\'s kanban activity. Highlight wins, blockers, and the top 3 priorities for this week.',
    state: 'scheduled',
    nextRun: (() => {
      const d = new Date()
      d.setDate(d.getDate() + (1 + 7 - d.getDay()) % 7)
      d.setHours(9, 0, 0, 0)
      return d.toISOString()
    })(),
    lastRun: new Date(Date.now() - 86400000 * 6).toISOString(),
    lastRunStatus: 'success',
    description: 'Weekly review of kanban progress.',
    createdBy: 'hermes',
  },
  {
    eventId: 'mock-audit-004',
    hermesJobId: 'mock-audit-004',
    scheduledAt: new Date(Date.now() + 86400000 * 2).toISOString(),
    title: 'Quarterly System Audit',
    type: 'planned',
    schedule: new Date(Date.now() + 86400000 * 2).toISOString(),
    scheduleDisplay: 'once at quarterly checkpoint',
    prompt: 'Run a full system audit: security review, cost optimization, dependency check.',
    state: 'scheduled',
    nextRun: new Date(Date.now() + 86400000 * 2).toISOString(),
    lastRunStatus: 'never',
    description: 'Full quarterly system audit.',
    createdBy: 'user',
  },
  {
    eventId: 'mock-logs-005',
    hermesJobId: 'mock-logs-005',
    scheduledAt: new Date().toISOString(),
    title: 'Log Cleanup Job',
    type: 'cron',
    schedule: '0 3 * * SUN',
    scheduleDisplay: '0 3 * * SUN',
    prompt: 'Purge log entries older than 30 days and compress weekly archives.',
    state: 'scheduled',
    nextRun: (() => {
      const d = new Date()
      d.setDate(d.getDate() + (7 - d.getDay()) % 7)
      d.setHours(3, 0, 0, 0)
      return d.toISOString()
    })(),
    lastRun: new Date(Date.now() - 86400000 * 5).toISOString(),
    lastRunStatus: 'failed',
    description: 'Purges expired log entries weekly.',
    createdBy: 'hermes',
  },
]

export const MOCK_ECS_LOGS = [
  { timestamp: Date.now() - 60000 * 5, message: '[INFO] Memory consolidation cycle started — 247 fragments queued' },
  { timestamp: Date.now() - 60000 * 4, message: '[OK] DynamoDB connection established — latency 12ms' },
  { timestamp: Date.now() - 60000 * 3, message: '[INFO] Processing task TX-0001: Analyze system performance metrics' },
  { timestamp: Date.now() - 60000 * 2, message: '[WARN] CPU utilization at 72% — approaching threshold' },
  { timestamp: Date.now() - 60000 * 1, message: '[INFO] Webhook received from integration: github.push event' },
  { timestamp: Date.now() - 30000, message: '[OK] Task TX-0005 marked complete — log rotation configured' },
  { timestamp: Date.now() - 15000, message: '[INFO] Memory index rebuilt — 6 entries indexed' },
  { timestamp: Date.now() - 5000, message: '[HERMES] Awaiting next scheduled run in 14m 32s' },
]
